# Loading the Libraries

## Loading the data

In [1]:
# Loading the Libraries
import pandas as pd
import numpy as np

In [2]:
# Loading the Excel file as a DataFrame.
df = pd.read_excel('WorkersComp-SA-15980-1-2.xlsx')

In [3]:
df.shape

(12305, 34)

In [4]:
pd.set_option("display.max_columns", 40)

In [5]:
# Checking the basic Stats of the data.
df.head()

,Claim #,Accident Date,Employer Code,Policy Year,Accident Year,Claim Received Year,Policy Written Premium,Class Code Desc,Last Surveyed,Claim Status,Accident State,General Cause of Injury,Cause of Injury,Accident Description,Part of Body,Claimant Average Weekly Wage,Claimant Occupation Description,Claimant Hire Date,Claimant Date Of Birth,Claimant DOB,Claim Received,Claim Closed Date,Days to Report,Loss Type,Paid Medical,Paid Expenses (Non-Medical),Total Recovery,Coverage State,Death_Claim,Claimant_Sex,Compensation Rate,Total Incurred,Total Net Paid,Reserves
0,CC001016845,2015-04-29,682880,2015,2015,2015,20784.0,Furniture or Fixtures Installation--Portable--NOC,2016-04-19,O,MD,Strain: General,STRAIN: HOLDING/CARRYING,Injured lower back loading wooden pallets,Lower Back Area (Incl. Lumbar &,677,FO Foreman,2015-01-03 00:00:00,1980-10-14 00:00:00,1980-10-14,2015-04-30,1900-01-01,1,LT,12283.46,7883.48,0.00,MD,N,M,452,66606.69,49998.94,16607.75
1,CC001015654,2014-06-10,507843,2014,2014,2014,55681.0,Furniture Mfg & Cabinet Shop,2014-02-21,C,NC,"POWERED HAND TOLL, APPLIANCE","POWERED HAND TOLL, APPLIANCE",Left index finger punctured when staple gun do...,FINGER(S),400,LA Laborer,2014-04-21 00:00:00,1953-09-06 00:00:00,1953-09-06,2014-06-13,2014-07-10,3,MO,1210.14,49.00,0.00,NC,N,M,0,1259.14,1259.14,0.00
2,CC001013744,2015-12-21,313522,2015,2015,2015,25871.0,"Concrete Work - Floors, Driveways - & Drivers",2015-09-15,C,SC,STRIKING: MOVING PARTS/MACHINE,STRIKING: MOVING PARTS/MACHINE,Injured right shoulder and forearm,MULTIPLE BODY PARTS,496.25,LA Laborer,2014-02-09 00:00:00,1972-12-09 00:00:00,1972-12-09,2015-12-23,2016-09-22,2,LT,7525.74,-12299.29,-151.66,SC,N,M,330.84,-151.66,-151.66,0.00
3,CC001016219,2014-01-27,305196,2013,2014,2014,68903.0,Fireproof Equipment Mfg.. Sheet Metal Products...,2013-08-20,C,NC,Struck: General,Struck or Injured By- Hand Tool or Machine in Use,Shot nail into left foot,FOOT,480,LA Laborer,2012-10-22 00:00:00,1988-05-27 00:00:00,1988-05-27,2014-02-03,2014-02-19,7,MO,1913.04,0.00,0.00,NC,N,M,0,1913.04,1913.04,0.00
4,CC001022377,2014-02-24,644443,2014,2014,2014,29374.0,Carpentry - Detached Dwellings,2016-05-03,C,NC,Falls: General,Fall or Slip - From Ladder or Screen,"Allegedly injured back, right foot and leg in ...",MULTIPLE BODY PARTS,0,SC Sub-Contractor,-,1988-09-06 00:00:00,1988-09-06,2014-09-12,2015-07-28,200,LT,0.00,6417.93,0.00,NC,N,M,0,6917.93,6917.93,0.00

## Understanding the Data

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12305 entries, 0 to 12304
Data columns (total 34 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Claim #                          12305 non-null  object
 1   Accident Date                    12305 non-null  object
 2   Employer Code                    12305 non-null  int64
 3   Policy Year                      12305 non-null  int64
 4   Accident Year                    12305 non-null  int64
 5   Claim Received Year              12305 non-null  int64
 6   Policy Written Premium           12300 non-null  float64
 7   Class Code Desc                  12305 non-null  object
 8   Last Surveyed                    12305 non-null  object
 9   Claim Status                     12305 non-null  object
 10  Accident State                   12305 non-null  object
 11  General Cause of Injury          12305 non-null  object
 12  Cause of Injury                  12305 non-null  object
 13  Accident Description             12305 non-null  object
 14  Part of Body                     12305 non-null  object
 15  Claimant Average Weekly Wage     12305 non-null  object
 16  Claimant Occupation Description  12305 non-null  object
 17  Claimant Hire Date               12305 non-null  object
 18  Claimant Date Of Birth           12305 non-null  object
 19  Claimant DOB                     12305 non-null  object
 20  Claim Received                   12305 non-null  object
 21  Claim Closed Date                12305 non-null  object
 22  Days to Report                   12305 non-null  int64
 23  Loss Type                        12305 non-null  object
 24  Paid Medical                     12305 non-null  float64
 25  Paid Expenses (Non-Medical)      12305 non-null  float64
 26  Total Recovery                   12305 non-null  float64
 27  Coverage State                   12305 non-null  object
 28  Death_Claim                      12305 non-null  object
 29  Claimant_Sex                     12305 non-null  object
 30  Compensation Rate                12305 non-null  object
 31  Total Incurred                   12305 non-null  float64
 32  Total Net Paid                   12305 non-null  float64
 33  Reserves                         12305 non-null  float64
dtypes: float64(7), int64(5), object(22)
memory usage: 3.2+ MB

- We can see that there are dates that are of object dtype.
- In "Policy Written Premium" There are 5 null values.

In [7]:
df.describe()

,Employer Code,Policy Year,Accident Year,Claim Received Year,Policy Written Premium,Days to Report,Paid Medical,Paid Expenses (Non-Medical),Total Recovery,Total Incurred,Total Net Paid,Reserves
count,12305.000000,12305.000000,12305.000000,12305.000000,1.230000e+04,12305.000000,1.230500e+04,12305.000000,12305.000000,1.230500e+04,1.230500e+04,1.230500e+04
mean,467325.279155,2014.631532,2015.039090,2015.077611,7.885086e+04,19.426087,7.490334e+03,810.506810,-40.883184,2.358152e+04,1.361613e+04,9.965388e+03
std,218118.597706,0.933560,0.811881,0.819686,1.601836e+05,53.137833,3.490911e+04,3284.426867,796.089772,1.057441e+05,4.996456e+04,7.522865e+04
min,100115.000000,2013.000000,2014.000000,2014.000000,0.000000e+00,0.000000,0.000000e+00,-137426.820000,-49367.390000,-3.902600e+02,-3.902600e+02,0.000000e+00
25%,277786.000000,2014.000000,2014.000000,2014.000000,1.334500e+04,1.000000,0.000000e+00,0.000000,0.000000,7.180000e+00,0.000000e+00,0.000000e+00
50%,464658.000000,2015.000000,2015.000000,2015.000000,3.195700e+04,5.000000,4.925300e+02,0.000000,0.000000,7.713100e+02,6.490000e+02,0.000000e+00
75%,648489.000000,2015.000000,2016.000000,2016.000000,8.328725e+04,14.000000,2.834670e+03,0.000000,0.000000,1.198236e+04,6.226520e+03,0.000000e+00
max,850889.000000,2016.000000,2016.000000,2017.000000,1.932224e+06,850.000000,1.413395e+06,63811.140000,0.000000,4.094406e+06,1.693212e+06,3.121409e+06

In [8]:
df.head()

,Claim #,Accident Date,Employer Code,Policy Year,Accident Year,Claim Received Year,Policy Written Premium,Class Code Desc,Last Surveyed,Claim Status,Accident State,General Cause of Injury,Cause of Injury,Accident Description,Part of Body,Claimant Average Weekly Wage,Claimant Occupation Description,Claimant Hire Date,Claimant Date Of Birth,Claimant DOB,Claim Received,Claim Closed Date,Days to Report,Loss Type,Paid Medical,Paid Expenses (Non-Medical),Total Recovery,Coverage State,Death_Claim,Claimant_Sex,Compensation Rate,Total Incurred,Total Net Paid,Reserves
0,CC001016845,2015-04-29,682880,2015,2015,2015,20784.0,Furniture or Fixtures Installation--Portable--NOC,2016-04-19,O,MD,Strain: General,STRAIN: HOLDING/CARRYING,Injured lower back loading wooden pallets,Lower Back Area (Incl. Lumbar &,677,FO Foreman,2015-01-03 00:00:00,1980-10-14 00:00:00,1980-10-14,2015-04-30,1900-01-01,1,LT,12283.46,7883.48,0.00,MD,N,M,452,66606.69,49998.94,16607.75
1,CC001015654,2014-06-10,507843,2014,2014,2014,55681.0,Furniture Mfg & Cabinet Shop,2014-02-21,C,NC,"POWERED HAND TOLL, APPLIANCE","POWERED HAND TOLL, APPLIANCE",Left index finger punctured when staple gun do...,FINGER(S),400,LA Laborer,2014-04-21 00:00:00,1953-09-06 00:00:00,1953-09-06,2014-06-13,2014-07-10,3,MO,1210.14,49.00,0.00,NC,N,M,0,1259.14,1259.14,0.00
2,CC001013744,2015-12-21,313522,2015,2015,2015,25871.0,"Concrete Work - Floors, Driveways - & Drivers",2015-09-15,C,SC,STRIKING: MOVING PARTS/MACHINE,STRIKING: MOVING PARTS/MACHINE,Injured right shoulder and forearm,MULTIPLE BODY PARTS,496.25,LA Laborer,2014-02-09 00:00:00,1972-12-09 00:00:00,1972-12-09,2015-12-23,2016-09-22,2,LT,7525.74,-12299.29,-151.66,SC,N,M,330.84,-151.66,-151.66,0.00
3,CC001016219,2014-01-27,305196,2013,2014,2014,68903.0,Fireproof Equipment Mfg.. Sheet Metal Products...,2013-08-20,C,NC,Struck: General,Struck or Injured By- Hand Tool or Machine in Use,Shot nail into left foot,FOOT,480,LA Laborer,2012-10-22 00:00:00,1988-05-27 00:00:00,1988-05-27,2014-02-03,2014-02-19,7,MO,1913.04,0.00,0.00,NC,N,M,0,1913.04,1913.04,0.00
4,CC001022377,2014-02-24,644443,2014,2014,2014,29374.0,Carpentry - Detached Dwellings,2016-05-03,C,NC,Falls: General,Fall or Slip - From Ladder or Screen,"Allegedly injured back, right foot and leg in ...",MULTIPLE BODY PARTS,0,SC Sub-Contractor,-,1988-09-06 00:00:00,1988-09-06,2014-09-12,2015-07-28,200,LT,0.00,6417.93,0.00,NC,N,M,0,6917.93,6917.93,0.00

### Checking Null values

In [9]:
# Checking for null value percentage
100* (df.isnull().sum() / len(df.index))

Claim #                            0.000000
Accident Date                      0.000000
Employer Code                      0.000000
Policy Year                        0.000000
Accident Year                      0.000000
Claim Received Year                0.000000
Policy Written Premium             0.040634
Class Code Desc                    0.000000
Last Surveyed                      0.000000
Claim Status                       0.000000
Accident State                     0.000000
General Cause of Injury            0.000000
Cause of Injury                    0.000000
Accident Description               0.000000
Part of Body                       0.000000
Claimant Average Weekly Wage       0.000000
Claimant Occupation Description    0.000000
Claimant Hire Date                 0.000000
Claimant Date Of Birth             0.000000
Claimant DOB                       0.000000
Claim Received                     0.000000
Claim Closed Date                  0.000000
Days to Report                     0.000000
Loss Type                          0.000000
Paid Medical                       0.000000
Paid Expenses (Non-Medical)        0.000000
Total Recovery                     0.000000
Coverage State                     0.000000
Death_Claim                        0.000000
Claimant_Sex                       0.000000
Compensation Rate                  0.000000
Total Incurred                     0.000000
Total Net Paid                     0.000000
Reserves                           0.000000
dtype: float64

### We can see the column Policy Written Premium has Null values.
- Since the Null valu is very less I will Impute them

In [10]:
# Checking the Null values in the 'Policy Written Premium' column.
df[df['Policy Written Premium'].isnull()]

,Claim #,Accident Date,Employer Code,Policy Year,Accident Year,Claim Received Year,Policy Written Premium,Class Code Desc,Last Surveyed,Claim Status,Accident State,General Cause of Injury,Cause of Injury,Accident Description,Part of Body,Claimant Average Weekly Wage,Claimant Occupation Description,Claimant Hire Date,Claimant Date Of Birth,Claimant DOB,Claim Received,Claim Closed Date,Days to Report,Loss Type,Paid Medical,Paid Expenses (Non-Medical),Total Recovery,Coverage State,Death_Claim,Claimant_Sex,Compensation Rate,Total Incurred,Total Net Paid,Reserves
1842,CC001016193,2015-06-09,372354,2015,2015,2015,NaN,"HVAC-Installation, Service and Repairs & Drivers",2014-06-12,C,NC,Cut,"CUT: HAND TOOL, NOT POWRD",Left wrist laceration after cutting self with ...,WRIST(S) & HAND(S),920,LA Laborer,-,1971-08-27 00:00:00,1971-08-27,2015-06-11,2015-06-11,2,NO,0.0,0.0,0.0,NC,N,M,0,0.0,0.0,0.0
1843,CC001026745,2015-06-09,372354,2015,2015,2015,NaN,"HVAC-Installation, Service and Repairs & Drivers",2014-06-12,C,NC,Cut,CUT: MISCELLANEOUS,Cut right hand on AC unit,HAND,600,AC A/C Installer,-,1975-05-05 00:00:00,1975-05-05,2015-06-11,2015-06-11,2,NO,0.0,0.0,0.0,NC,N,M,0,0.0,0.0,0.0
2822,CC001027983,2016-09-15,482918,2016,2016,2016,NaN,"HVAC-Installation, Service and Repairs & Drivers",-,C,NC,-,OTHER,"Claimant grabbed right arm, fell down and seiz...",Body System/Multiple Body Systems,1230,AC A/C Installer,2005-03-16 00:00:00,1960-06-17 00:00:00,1960-06-17,2016-09-20,2016-09-20,5,NO,0.0,0.0,0.0,NC,N,M,0,0.0,0.0,0.0
10132,CC001016717,2016-07-25,334727,2016,2016,2016,NaN,"HVAC-Installation, Service and Repairs & Drivers",2016-05-18,C,NC,Cut,"CUT: HAND TOOL, NOT POWRD",Screwdriver hit left eye,EYE(S),400,LA Laborer,2016-07-18 00:00:00,1976-01-22 00:00:00,1976-01-22,2016-07-26,2016-07-26,1,NO,0.0,0.0,0.0,NC,N,M,0,0.0,0.0,0.0
11277,CC001012937,2015-08-28,705948,2015,2015,2015,NaN,Roofing - All kinds & Drivers,2016-10-12,C,TN,Strain: General,STRAIN: MISCELLANEOUS,Chrushed left thumb in metal.,THUMB,125.25,LA Laborer,2014-02-17 00:00:00,1980-11-12 00:00:00,1980-11-12,2015-09-02,2015-09-02,5,MO,0.0,0.0,0.0,TN,N,M,125.25,0.0,0.0,0.0

In [11]:
# Since there are no values related to revenue and the status of the claim is Claimed I amremoving these 5 rows.
df.dropna(subset=['Policy Written Premium'], inplace=True)

In [12]:
# Checking the results.
df.isnull().sum()

Claim #                            0
Accident Date                      0
Employer Code                      0
Policy Year                        0
Accident Year                      0
Claim Received Year                0
Policy Written Premium             0
Class Code Desc                    0
Last Surveyed                      0
Claim Status                       0
Accident State                     0
General Cause of Injury            0
Cause of Injury                    0
Accident Description               0
Part of Body                       0
Claimant Average Weekly Wage       0
Claimant Occupation Description    0
Claimant Hire Date                 0
Claimant Date Of Birth             0
Claimant DOB                       0
Claim Received                     0
Claim Closed Date                  0
Days to Report                     0
Loss Type                          0
Paid Medical                       0
Paid Expenses (Non-Medical)        0
Total Recovery                     0
Coverage State                     0
Death_Claim                        0
Claimant_Sex                       0
Compensation Rate                  0
Total Incurred                     0
Total Net Paid                     0
Reserves                           0
dtype: int64

### Data Pre-Processing

#### Since we have Claimant DOB I am removing the Claimant Date Of Birth column

In [13]:
df.drop('Claimant Date Of Birth', axis=1, inplace = True)

#### Changing the Claim status, Death_Claim, and Claimant_Sex for easier understanding.

In [14]:
df['Claim Status'].value_counts()

C    10534
O     1766
Name: Claim Status, dtype: int64

In [15]:
df['Death_Claim'].value_counts()

N    12258
Y       42
Name: Death_Claim, dtype: int64

In [16]:
df['Claimant_Sex'].value_counts()

M             11872
F               402
                 19
N                 7
Name: Claimant_Sex, dtype: int64

- I am going to change these values into more understandable values.
- There are also some values which are not eplained in the Claimant_Sex, so I am changing them into 'Unknown'

In [17]:
df['Claim Status'] = np.where(df['Claim Status'] == 'C', 'Closed', df['Claim Status'])
df['Claim Status'] = np.where(df['Claim Status'] == 'O', 'Open', df['Claim Status'])

df['Death_Claim'] = np.where(df['Death_Claim'] == 'Y', 'Yes', df['Death_Claim'])
df['Death_Claim'] = np.where(df['Death_Claim'] == 'N', 'No', df['Death_Claim'])

df['Claimant_Sex'] = df['Claimant_Sex'].map(
    lambda x: 'Female' if x == 'F' else ('Male' if x == 'M'  else 'Unknown'))

In [18]:
df['Claimant_Sex'].value_counts()

Male       11872
Female       402
Unknown       26
Name: Claimant_Sex, dtype: int64

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12300 entries, 0 to 12304
Data columns (total 33 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Claim #                          12300 non-null  object
 1   Accident Date                    12300 non-null  object
 2   Employer Code                    12300 non-null  int64
 3   Policy Year                      12300 non-null  int64
 4   Accident Year                    12300 non-null  int64
 5   Claim Received Year              12300 non-null  int64
 6   Policy Written Premium           12300 non-null  float64
 7   Class Code Desc                  12300 non-null  object
 8   Last Surveyed                    12300 non-null  object
 9   Claim Status                     12300 non-null  object
 10  Accident State                   12300 non-null  object
 11  General Cause of Injury          12300 non-null  object
 12  Cause of Injury                  12300 non-null  object
 13  Accident Description             12300 non-null  object
 14  Part of Body                     12300 non-null  object
 15  Claimant Average Weekly Wage     12300 non-null  object
 16  Claimant Occupation Description  12300 non-null  object
 17  Claimant Hire Date               12300 non-null  object
 18  Claimant DOB                     12300 non-null  object
 19  Claim Received                   12300 non-null  object
 20  Claim Closed Date                12300 non-null  object
 21  Days to Report                   12300 non-null  int64
 22  Loss Type                        12300 non-null  object
 23  Paid Medical                     12300 non-null  float64
 24  Paid Expenses (Non-Medical)      12300 non-null  float64
 25  Total Recovery                   12300 non-null  float64
 26  Coverage State                   12300 non-null  object
 27  Death_Claim                      12300 non-null  object
 28  Claimant_Sex                     12300 non-null  object
 29  Compensation Rate                12300 non-null  object
 30  Total Incurred                   12300 non-null  float64
 31  Total Net Paid                   12300 non-null  float64
 32  Reserves                         12300 non-null  float64
dtypes: float64(7), int64(5), object(21)
memory usage: 3.2+ MB

#### Changing the Date columns from object into Datetime columns.

In [20]:
df['Claimant DOB'] = pd.to_datetime(df['Claimant DOB']).dt.date
df['Accident Date'] = pd.to_datetime(df['Accident Date']).dt.date
df['Claimant DOB'] = pd.to_datetime(df['Claimant DOB']).dt.date
df['Claim Closed Date'] = pd.to_datetime(df['Claim Closed Date']).dt.date

In [21]:
df['Claimant Age'] =round((df['Accident Date']- df['Claimant DOB'] )/ np.timedelta64(1, 'Y'),0)

## Saving the updated Data

In [22]:
df[['Claimant Age']]

       Claimant Age
0              35.0
1              61.0
2              43.0
3              26.0
4              25.0
...             ...
12300          39.0
12301          48.0
12302          34.0
12303          23.0
12304          38.0

[12300 rows x 1 columns]

### I dont see much other problems. So, now we can save the updated CSV file and do some visualisations.

In [23]:
df.to_csv("WorkersComp-SA-15980-1-2Updated.csv", index=False)

                                                           End                                                           .